### ISSUE TITLE
How to build the iOS folder ?

### ISSUE THREAD

**Issue by SkYNewZ** [alxreed/on_regarde_quoi_ce_soir#1]
Hi,
I want to build this app for iOS. So, I've open the `Runner.xcworkspace` with Xcode. When building, its says `ios/Flutter/Debug.xcconfig:1: could not find included file 'Generated.xcconfig' in search paths`.

Notice: I don't know Flutter.

Thanks

**Comment by alxreed** [comment]
Sorry this app is not finished yet. I'm still learning flutter and had never build this for IOS yet.

**Comment by SkYNewZ** [comment]
Okay, thank you for that specific answer. Good luck! 😉
